'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AlertCircle, BookOpen, Plus, X } from 'lucide-react';
import BunkCalculatorCard from '@/components/subject/BunkCalculatorCard';

interface SubjectData { id: string; name: string; code?: string | null; color: string; targetPercentage: number; stats: any }
const COLORS = ['#6366f1', '#06b6d4', '#10b981', '#f59e0b', '#ec4899', '#8b5cf6', '#ef4444', '#3b82f6'];

export default function SubjectsPage() {
  const [subjects, setSubjects] = useState<SubjectData[]>([]), [loading, setLoading] = useState(true), [hasSemester, setHasSemester] = useState<boolean | null>(null);
  const [modal, setModal] = useState<'add' | 'edit' | null>(null), [editing, setEditing] = useState<SubjectData | null>(null), [name, setName] = useState(''), [code, setCode] = useState(''), [color, setColor] = useState(COLORS[0]), [target, setTarget] = useState('75'), [error, setError] = useState('');
  const load = async () => { try { setLoading(true); const [subjectRes, termRes] = await Promise.all([fetch('/api/subjects'), fetch('/api/semesters')]); const subjectData = await subjectRes.json(), termData = await termRes.json(); setSubjects(subjectData.subjects ?? []); setHasSemester(Boolean(termData.activeSemester)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const openAdd = () => { setEditing(null); setName(''); setCode(''); setColor(COLORS[0]); setTarget('75'); setError(''); setModal('add'); };
  const openEdit = (subject: SubjectData) => { setEditing(subject); setName(subject.name); setCode(subject.code ?? ''); setColor(subject.color); setTarget(String(subject.targetPercentage)); setError(''); setModal('edit'); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/subjects', { method: modal === 'edit' ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: editing?.id, name, code, color, targetPercentage: target }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? 'Unable to save subject.'); return; } setModal(null); await load(); };
  const remove = async (subject: SubjectData) => { if (!window.confirm(`Delete ${subject.name} and its lecture history? This cannot be undone.`)) return; const response = await fetch(`/api/subjects?id=${subject.id}`, { method: 'DELETE' }); if (response.ok) await load(); else { const result = await response.json(); window.alert(result.error ?? 'Unable to delete subject.'); } };
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 glass-card p-5 rounded-2xl"><div className="flex items-center gap-4"><div className="h-12 w-12 rounded-xl bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400"><BookOpen className="h-6 w-6" /></div><div><h2 className="text-xl font-bold text-white">Subjects & Attendance</h2><p className="text-xs text-gray-400">Track each subject’s attendance target and safe skips.</p></div></div>{hasSemester && <button onClick={openAdd} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-xs"><Plus className="h-4 w-4" />Add subject</button>}</div>
    {!hasSemester ? <div className="glass-card rounded-2xl p-12 text-center"><BookOpen className="h-8 w-8 mx-auto text-indigo-400 mb-3" /><h3 className="text-lg font-bold text-white">Create a term first</h3><p className="text-sm text-gray-400 mt-2 mb-5">Subjects belong to a semester so their attendance stays organised.</p><Link href="/timetable" className="inline-flex px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-sm font-semibold">Go to Timetable Builder</Link></div> : subjects.length === 0 ? <div className="glass-card rounded-2xl p-12 text-center"><BookOpen className="h-8 w-8 mx-auto text-indigo-400 mb-3" /><h3 className="text-lg font-bold text-white">No subjects yet</h3><p className="text-sm text-gray-400 mt-2 mb-5">Add subjects here or type their names while adding timetable lectures.</p><button onClick={openAdd} className="px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-sm font-semibold">Add first subject</button></div> : <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">{subjects.map((subject) => <BunkCalculatorCard key={subject.id} subjectName={subject.name} code={subject.code} color={subject.color} stats={subject.stats} onEdit={() => openEdit(subject)} onDelete={() => remove(subject)} />)}</div>}
    {modal && <div className="fixed inset-0 z-50 bg-[#0b0f17]/80 backdrop-blur-md flex items-center justify-center p-4"><div className="glass-card rounded-2xl max-w-md w-full p-6"><div className="flex items-center justify-between border-b border-white/10 pb-3 mb-4"><h3 className="font-bold text-lg text-white">{modal === 'edit' ? 'Edit subject' : 'Add subject'}</h3><button onClick={() => setModal(null)} className="text-gray-400 hover:text-white"><X className="h-5 w-5" /></button></div>{error && <div className="p-3 mb-4 rounded-xl bg-rose-500/20 text-rose-300 text-xs flex gap-2"><AlertCircle className="h-4 w-4" />{error}</div>}<form onSubmit={save} className="space-y-4 text-xs"><div><label className="block text-gray-400 mb-1">Subject name</label><input required value={name} onChange={(e) => setName(e.target.value)} className="w-full p-2.5 rounded-xl bg-[#0b0f17] border border-white/10 text-white" /></div><div><label className="block text-gray-400 mb-1">Subject code (optional)</label><input value={code} onChange={(e) => setCode(e.target.value)} className="w-full p-2.5 rounded-xl bg-[#0b0f17] border border-white/10 text-white" /></div><div><label className="block text-gray-400 mb-1">Target attendance (%)</label><input required type="number" min="1" max="100" value={target} onChange={(e) => setTarget(e.target.value)} className="w-full p-2.5 rounded-xl bg-[#0b0f17] border border-white/10 text-white" /></div><div><label className="block text-gray-400 mb-2">Colour</label><div className="flex gap-2 flex-wrap">{COLORS.map((value) => <button key={value} type="button" onClick={() => setColor(value)} className={`h-7 w-7 rounded-full border-2 ${color === value ? 'border-white scale-110' : 'border-transparent'}`} style={{ backgroundColor: value }} />)}</div></div><div className="flex justify-end gap-2"><button type="button" onClick={() => setModal(null)} className="px-4 py-2 rounded-xl bg-white/5 text-gray-300">Cancel</button><button className="px-4 py-2 rounded-xl bg-indigo-600 text-white">{modal === 'edit' ? 'Save changes' : 'Save subject'}</button></div></form></div></div>}
  </div>;
}
