'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Zap } from 'lucide-react';

export default function AuthForm({ mode }: { mode: 'login' | 'signup' | 'verify' }) {
  const router = useRouter(); const [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [code, setCode] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); const path = mode === 'verify' ? '/api/auth/verify' : `/api/auth/${mode}`; const body = mode === 'verify' ? { email, code } : mode === 'signup' ? { name, email, password } : { email, password }; const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.error || 'Something went wrong.'); if (data.verificationRequired || mode === 'signup') return router.push(`/verify-email?email=${encodeURIComponent(data.email || email)}`); router.push('/'); router.refresh(); };
  return <main className="min-h-screen flex items-center justify-center p-5 bg-[#0b0f17]"><div className="w-full max-w-md glass-card rounded-2xl p-7 border border-white/10"><div className="flex items-center gap-3 mb-7"><div className="h-10 w-10 rounded-xl bg-gradient-to-tr from-indigo-600 to-cyan-400 flex items-center justify-center"><Zap className="h-5 w-5 text-white" /></div><div><h1 className="font-bold text-xl text-white">Attend<span className="text-cyan-300">IQ</span></h1><p className="text-xs text-gray-400">Attendance made simple</p></div></div><h2 className="text-xl font-bold text-white">{mode === 'signup' ? 'Create your account' : mode === 'verify' ? 'Verify your email' : 'Welcome back'}</h2><p className="text-sm text-gray-400 mt-1 mb-5">{mode === 'verify' ? 'Enter the six-digit code sent to your email.' : mode === 'signup' ? 'Use your email to get started.' : 'Sign in to your timetable and attendance.'}</p>{error && <p className="mb-4 p-3 rounded-xl bg-rose-500/20 text-rose-300 text-xs">{error}</p>}<form onSubmit={submit} className="space-y-4 text-sm">{mode === 'signup' && <input required placeholder="Your name" value={name} onChange={(e) => setName(e.target.value)} className="w-full p-3 rounded-xl bg-[#0b0f17] border border-white/10 text-white" />}<input required type="email" placeholder="Email address" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full p-3 rounded-xl bg-[#0b0f17] border border-white/10 text-white" />{mode === 'verify' ? <input required inputMode="numeric" maxLength={6} placeholder="6-digit verification code" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} className="w-full p-3 rounded-xl bg-[#0b0f17] border border-white/10 text-white tracking-[0.4em]" /> : <input required type="password" minLength={8} placeholder="Password (8+ characters)" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full p-3 rounded-xl bg-[#0b0f17] border border-white/10 text-white" />}<button disabled={loading} className="w-full p-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-60 text-white font-semibold">{loading ? 'Please wait…' : mode === 'signup' ? 'Create account' : mode === 'verify' ? 'Verify email' : 'Sign in'}</button></form>{mode !== 'verify' && <p className="text-center text-xs text-gray-400 mt-5">{mode === 'login' ? <>New here? <Link className="text-cyan-300" href="/signup">Create an account</Link></> : <>Already have an account? <Link className="text-cyan-300" href="/login">Sign in</Link></>}</p>}</div></main>;
}
